// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM3xENHRNejote8-mm4oDuimv7wQT3OVc',
    appId: '1:290491391075:web:a7383f1a27683fb2a92c56',
    messagingSenderId: '290491391075',
    projectId: 'todo-app-b6d44',
    authDomain: 'todo-app-b6d44.firebaseapp.com',
    storageBucket: 'todo-app-b6d44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsIIsNDFZFN1H3B9cM7Mu_uMxqSCfNVRA',
    appId: '1:290491391075:android:8d76cc26c0da4794a92c56',
    messagingSenderId: '290491391075',
    projectId: 'todo-app-b6d44',
    storageBucket: 'todo-app-b6d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPGbManU4LCa9-hqIQ93pod0m8R2IhHs',
    appId: '1:290491391075:ios:ecfda2060b2c0258a92c56',
    messagingSenderId: '290491391075',
    projectId: 'todo-app-b6d44',
    storageBucket: 'todo-app-b6d44.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
